# Github actions to upload to GH Packages an Angular Library with Storybook and publish it

name: Excelsior-Angular
on:
  # Trigger with manual action
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@accentiostudios'

      - name: Install dependencies
        run: npm ci
      - name: Build and Test
        run: npm run build

      - name: Build Storybook
        run: npm run storybook:build

      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
